### NumPy Arrays

In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
type(mylist)

list

In [7]:
arr = np.array(mylist)
arr

array([1, 2, 3])

In [8]:
type(arr)

numpy.ndarray

In [9]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
mymatrix = np.array(mylist)

In [13]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
mymatrix.shape

(3, 3)

In [16]:
mynewmatrix = np.array(mylist)

In [17]:
mynewmatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
type(0.)

float

In [22]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((5,5)) + 4 
# this con not done in normal python list, so peoples are use numpy array

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [26]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [29]:
[1,1,1,1] + 10 
# we cant do this in list

TypeError: can only concatenate list (not "int") to list

In [30]:
np.ones(4) + 100

array([101., 101., 101., 101.])

In [31]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

In [33]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [34]:
len(np.linspace(0,10,20))

20

In [35]:
np.arange(0,10,20)

array([0])

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(4) # uniform distribution

array([0.90700936, 0.50213844, 0.71103737, 0.05155349])

In [39]:
np.random.rand(5,5) # uniform distribution

array([[0.10742912, 0.50674465, 0.77754861, 0.09365402, 0.33401193],
       [0.28562605, 0.87255761, 0.98316701, 0.58281507, 0.68839962],
       [0.78810736, 0.14997868, 0.45198184, 0.02891045, 0.79554801],
       [0.70144356, 0.7562038 , 0.15578719, 0.55217413, 0.71117378],
       [0.49932915, 0.76738626, 0.42620658, 0.8896056 , 0.81504364]])

In [42]:
np.random.randn(10) # normal ditributed

array([ 0.15854589, -0.13192466, -0.85369755,  0.54855477,  0.03070691,
        0.11500419, -0.28493543, -1.43482144,  1.48585363,  0.32352842])

In [47]:
""" np.random.normal is a function in the NumPy library in Python
that generates random numbers from a normal (Gaussian) distribution"""
np.random.normal

<function RandomState.normal>

In [50]:
arr = np.random.normal(0,3,5)
arr

array([-0.06830852,  0.35006079, -1.49016058, -0.46313678,  5.55967357])

In [61]:
np.random.randint(1,100,10)

array([81, 85, 47, 74, 90, 87, 12, 26, 85, 15])

In [68]:
np.random.seed(555) # This ensures that the sequence of random numbers generated will be the same every time you run the code, which can be useful for reproducibility.
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [69]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [111]:
arr=np.arange(25)

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [113]:
ranarr = np.random.randint(0,50,10)

In [114]:
ranarr

array([38, 43, 34, 40, 32, 46, 36,  1, 35,  7])

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [116]:
arr.shape

(25,)

In [117]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
ranarr.max()

46

In [119]:
ranarr.min()

1

In [120]:
ranarr.argmax()

5

In [121]:
ranarr.argmin()

7

In [122]:
ranarr.dtype

dtype('int32')

In [123]:
# Index and selection

In [124]:
arr=np.arange(0,11)

In [125]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr[8]

8

In [127]:
arr[1:5]

array([1, 2, 3, 4])

In [128]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [129]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [130]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
arr_copy =arr.copy()

In [132]:
arr_copy[:] = 10

In [135]:
arr_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [136]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
# indexing on 2d array                                                                   wwwwwwwwwwwww

In [138]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])


In [139]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [140]:
arr_2d.ndim

2

In [141]:
arr_2d.shape

(3, 3)

In [142]:
arr_2d[1]

array([20, 25, 30])

In [143]:
arr_2d[1][1]

25

In [144]:
arr_2d[1,1]

25

In [145]:
arr_2d[2][2]

45

In [146]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [147]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [148]:
arr=np.arange(1,11)

In [149]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [153]:
bool_arr = arr > 4

In [154]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [155]:
arr[bool_arr] # only True will disply 

array([ 5,  6,  7,  8,  9, 10])

In [156]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [157]:
arr[arr==2]

array([2])

In [159]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])

In [160]:
# Numpy Opeartaions

In [161]:
arr = np.arange(0,10)

In [162]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [164]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [165]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [166]:
(arr+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [167]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [168]:
1/arr # gives us the warning not error for "divided by zero"

C:\Users\Digvijay Mohite\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [169]:
arr/arr # error not comes due to 0/0 = nan, it is giving the warning to us

C:\Users\Digvijay Mohite\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [170]:
# we still see an output after giving error comes in warning

In [171]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [172]:
np.log(arr) # still outcome come log(o)=-inf

C:\Users\Digvijay Mohite\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [173]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [174]:
arr.sum()

45

In [175]:
arr.mean()

4.5

In [176]:
arr.max()

9

In [180]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [181]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [182]:
arr_2d.shape

(3, 4)

In [183]:
arr_2d.sum()

78

In [184]:
arr_2d.sum(axis=0) # sum across the rows

array([15, 18, 21, 24])

In [185]:
arr_2d.sum(axis=1) # sum across the columns

array([10, 26, 42])